// Generated by CoffeeScript 1.9.3
(function() {
  window.SB = (function() {
    function SB() {}

    SB.init = function() {
      this.initSiteNav();
      this.initAboutPage();
      return this.initPeoplePage();
    };

    SB.initSiteNav = function() {
      return $('.site-nav a').click(function() {
        $('.active').toggleClass("active");
        return $('#' + this.dataset.targetPage).toggleClass("active");
      });
    };

    SB.initAboutPage = function() {
      var $caption, $gallery, flkty;
      $gallery = $('.gallery').flickity({
        cellSelector: 'img',
        imagesLoaded: true,
        percentPosition: false
      });
      $caption = $('.caption');
      flkty = $gallery.data('flickity');
      return $gallery.on('cellSelect', function() {
        return $caption.text(flkty.selectedElement.alt);
      });
    };

    SB.initPeoplePage = function() {
      var $container;
      $container = $('.js-isotope').isotope({
        itemSelector: '.person',
        layoutMode: 'masonry',
        getSortData: {
          name: '.person__name',
          floor: '[data-floor]'
        },
        sortAscending: {
          name: true,
          floor: false
        },
        sortBy: 'random'
      });
      $('#filters li').click(function() {
        var filterValue;
        filterValue = $(this).attr('data-filter');
        return $container.isotope({
          filter: filterValue
        });
      });
      $('#sorts li').click(function() {
        var sortValue;
        sortValue = $(this).attr('data-sort');
        return $container.isotope({
          sortBy: sortValue
        });
      });
      $('.person').click(function() {
        return $('.cards').fadeIn();
      });
      return $('.card__close').click(function() {
        return $('.cards').fadeOut();
      });
    };

    return SB;

  })();

  (function($) {
    return SB.init();
  })(jQuery);

}).call(this);
