// Generated by CoffeeScript 1.9.3
(function() {
  window.SB = (function() {
    function SB() {}

    SB.init = function() {
      this.initSiteNav();
      return this.initPeoplePage();
    };

    SB.initSiteNav = function() {
      return $('.site-nav a').click(function() {
        $('.active').toggleClass("active");
        return $('#' + this.dataset.targetPage).toggleClass("active");
      });
    };

    SB.initPeoplePage = function() {
      return console.log("People!");
    };

    return SB;

  })();

  (function($) {
    return SB.init();
  })(jQuery);

}).call(this);
